# Jekyll configuration; see https://github.com/mojombo/jekyll/wiki/Configuration
# Note: Jekyll configuration settings may not be respected by GitHub Pages.
# Read the friendly manual: https://help.github.com/articles/using-jekyll-with-pages


# Course-site specific configuration:
course:
  # Enter a base path if needed; not necessary for testing at localhost:4000/
  # or if your site is hosted at a simple URL like http://example.com/
  # But, if something comes after the .com/, you should enter it here.
  # E.g., for http://example.com/530/ you'd enter 530/ for base_path:
  base_path: dsam2025fall/
  # base_path: /
  # E.g., ENGL 536
  number: DSAM 3000 / HAA 2045
  name: Digital Studies and Methods – Seminar
  university: University of Pittsburgh
  # Keep the description brief, about 140 chars
  description: Computing with humans and humanizing with computers
  # E.g., Spring 2013:
  term: Fall 2025
  slugterm: 2025fall
  time: M 9:00-11:50am
  room: Cathedral of Learning 329 or by Zoom in case of emergency
  dml_hours: t.b.d.
  featured_image: course-title.png
  featured_alt: a network of multicultural people connected by strings of code, line-art style (image generated by dreamstudio ai)
  instructor:
    name: Benjamin Miller
    office: CL 617-N and Zoom
    office_hours: M/Th 12:30-2:00pm or by appointment
    email: millerb@pitt.edu
    # No @ before your username; e.g., twitter, not @twitter
    twitter: benmiller314
# github: [metadata]
github_url: https://benmiller314.github.io/dsam2025fall
repo_url: https://github.com/benmiller314/dsam2025fall
canvas_url: https://canvas.pitt.edu/courses/327056
theme: jekyll-theme-time-machine
